language: python
python: "3.6"
install:
  - pip install git+https://github.com/OpenDreamKit/planetaryum.git
script:
  - planetaryum static title="Algèbre Commutative et Effective – MA2 ACE" baseurl="https://github.com/defeo/MA2-ace-notebooks/raw/master/%" binderurl="https://mybinder.org/v2/gh/defeo/MA2-ace-notebooks/master?filepath=%"
deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
